### ISSUE TITLE
Safari scroll bouncing causes white space to appear

### ISSUE THREAD

**Issue by matheusgrieger** [KyleAMathews/react-headroom#195]
When scrolling too fast or too much to the top of the page in desktop Safari, it shows an extra white space as is expected, but that locks the header out of place, as can be seen in the image below (notice the highlighted element is actually below the highlight).

Does anyone knows a way to fix this? Seems related to #89.

![image](https://user-images.githubusercontent.com/6992464/103091264-641cf480-45d2-11eb-8581-5f687ad96c4a.png)

Edit: just saw that #90 aimed to fix this but it still happens to me on 3.1.0

**Comment by LiteSoul** [comment]
The same is happening to me on Safari. Using the latest react-headroom release 3.1.0 as well as 2.2.8

**Comment by cheezywhiz** [comment]
Just started seeing this behavior after upgrading to Big Sur/Safari 14. Weird thing is that the mouse still responds as if the header is in the right place.

<img width="1211" alt="oops" src="https://user-images.githubusercontent.com/3833605/103568390-4d03bf80-4e7a-11eb-9022-2d13e530a8a5.png">

I'm using <Headroom disable={isSafari && !isMobile}> until there's a fix.

**Comment by tannerbaum** [comment]
We also have been experiencing this for a few months now. Observed that is wasn't an issue in Safari 13, only in 14.

**Comment by matheusgrieger** [comment]
I'm starting to think that it's a Safari glitch, not related to the library itself.

**Comment by meaghanbass** [comment]
@cheezywhiz Can you share how you got isSafari and isMobile?

**Comment by cheezywhiz** [comment]
> @cheezywhiz Can you share how you got isSafari and isMobile?

@meaghanbass I'm using https://www.npmjs.com/package/react-device-detect for that

**Comment by smeriwether** [comment]
I was seeing the same issue but was able to get this working by passing in `position: fixed` to the `style` prop. My component now looks like this:

```js
<Headroom style={{ zIndex: 100, position: "fixed" }}>
...
</Headroom>
```

**Comment by cheezywhiz** [comment]
@smeriwether amazing! confirming that this works. thanks!!

**Comment by opolo** [comment]
Struck by the same problem in production. Setting position fixed solves it, but ruins all the "animations" on the header, which kinda moots the point of using headroom for having a visually pleasing behaving header.

Have anyone found any other fixes to this?

**Comment by cheezywhiz** [comment]
seems to work fine now with 3.1.1

**Comment by matheusgrieger** [comment]
Yes, this is solved now. Thanks guys!

**Comment by chaddjohnson** [comment]
This is still a problem with react-headroom 3.2.0 in Safari.

**Comment by endymion1818** [comment]
Hello @chaddjohnson please could you let me know what version of Safari you're on

**Comment by chaddjohnson** [comment]
@endymion1818 Version 15.1 (17612.2.9.1.20)

BTW, is your name a Hyperion reference?

**Comment by endymion1818** [comment]
Ok thanks.

Yes it is! I've been fascinated with John Keats ever since I read Dan Simmons' novels some years ago.

**Comment by bamerf** [comment]
This is still an issue with react-headroom 3.2.0 and Safari 15.4 (17613.1.17.1.13)

**Comment by endymion1818** [comment]
Well, darnit.
